spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5433/appdb?ssl=false&sslmode=disable&tcpKeepAlive=true&connectTimeout=30&loginTimeout=10
    username: app
    password: dockWord123
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 20000
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true

# JWT Configuration
app:
  jwt:
    secret: ${JWT_SECRET}
    expiration: 10800000  # 30 minutes in milliseconds, during dev to 3 hours incremented
